### ISSUE TITLE
How to overwrite / translate form.label.adyen_ideal

### ISSUE THREAD

**Issue by roelleor** [ruudk/PaymentAdyenBundle#9]
Hi Ruud,
The question is in the title, since JMS is not assigning any translation bundles, how do I go about this?
Thanks!

**Comment by ruudk** [comment]
Add `form.label.adyen_ideal: my-value` to `AppBundle/Resources/translations/jms_payment.en.yml`

**Comment by roelleor** [comment]
Thanks for your reply! With AppBundle I presume you mean the bundle that's being used to render the jms_choose_payment_method formtype from? This does not seem to be working. Adding the file to App/Resources/translations doesn't work either.

**Comment by ruudk** [comment]
I guess, then you need to override the translations of JMS via http://symfony.com/doc/current/cookbook/bundles/override.html

**Comment by roelleor** [comment]
Hi Ruud,

Found the answer, you can just add the translation_domain as an option to the form. Thanks for your time, you can close this issue.

Roel
